/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramePrueba.java
 *
 * Created on 20/01/2010, 12:47:45 PM
 */

package prueba;

import com.jturingmachinele.graphics.estados.EstadoInicial;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;

/**
 *
 * @author jsandoval
 */
public class FramePrueba extends javax.swing.JFrame {
EstadoInicial ei = null;
boolean band = false;
    /** Creates new form FramePrueba */
    public FramePrueba() {
        initComponents();
        ei = EstadoInicial.getInstancia(new Point(150,150), "q1");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Exitar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jToggleButton1)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButton1))
                .addGap(295, 295, 295))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //public void paint(Graphics g){
        
            int x = Integer.parseInt(JOptionPane.showInputDialog(this, "x"));
            int y = Integer.parseInt(JOptionPane.showInputDialog(this, "y"));
            ei.setCoordenadaXY(new Point(x,y));
            ei.delimitarArea();
            ei.formarPuertos();
            this.repaint();
        //}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton1.isSelected()){
            ei.exitar();
            this.repaint();
        }else{
            ei.desexitar();
            this.repaint();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed
boolean banderaMov = false;
boolean banderaDOS = true;
    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        //System.out.println(String.format("[%1$d,%2$d]",evt.getX(), evt.getY()));
        //System.out.println(String.format("[%1$d,%2$d]",ei.getCoordenadaXY().x, ei.getCoordenadaXY().y));
        bandera = false;//Bandera de arrastrar
        
        if(ei.isFlotando(evt.getX(), evt.getY())){
            banderaMov = true;
        }else{
            banderaMov = false;
        }
        if(banderaMov){
            if(banderaDOS){
                ei.exitar();
                this.repaint();
            }
            banderaDOS = false;
        }
        if(!banderaMov && !banderaDOS){
            ei.desexitar();
            this.repaint();
            banderaDOS = true;
        }
//        if(ei.isFlotando(evt.getX(), evt.getY())){
//           // band = false;;
//            ei.exitar();
//            this.repaint();
//        }else{
//            band = false;
//            ei.desexitar();
//            this.repaint();
//        }
//        if(band){
//            this.repaint();
//            band = false;
//        }
    }//GEN-LAST:event_formMouseMoved
boolean bandera = false;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:

        if(ei.isFlotando(evt.getX(), evt.getY()) && bandera == false){
            bandera = true;
        }
        if(bandera){
            ei.setCoordenadaXY(new Point(evt.getX() - EstadoInicial.RADIO, evt.getY() - EstadoInicial.RADIO));
            ei.delimitarArea();
            ei.formarPuertos();
            this.repaint();
        }

    }//GEN-LAST:event_formMouseDragged


    @Override
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2d=(Graphics2D)g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        //g2d.scale(2, 2);
        ei.dibujar(g);
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
